using UnityEngine;

namespace NightHunt.Gameplay.Map
{
    /// <summary>
    /// Marker for colliders generated by the map collision setup editor tool.
    /// Keeping a marker lets the tool clear and rebuild generated colliders safely.
    /// </summary>
    [DisallowMultipleComponent]
    public sealed class NightHuntAutoMapCollider : MonoBehaviour
    {
        [SerializeField] private string _sourceRendererPath;
        [SerializeField] private string _classification;
        [SerializeField] private string _generatedBy = "NightHuntMapCollisionSetupTool";

        public string SourceRendererPath => _sourceRendererPath;
        public string Classification => _classification;
        public string GeneratedBy => _generatedBy;

        public void Initialize(string sourceRendererPath, string classification)
        {
            _sourceRendererPath = sourceRendererPath;
            _classification = classification;
            _generatedBy = "NightHuntMapCollisionSetupTool";
        }
    }
}
